name: Test Suite

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black mypy
          
      - name: Lint with flake8
        run: |
          flake8 src/ tests/ --max-line-length=120 --ignore=E203,W503
          
      - name: Check formatting with black
        run: |
          black --check src/ tests/
          
      - name: Type check with mypy
        run: |
          mypy src/ --ignore-missing-imports || true

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v5
  #     
  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.9'
  #         
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt
  #         
  #     - name: Run tests
  #       run: |
  #         python -m pytest tests/ -v --cov=src --cov-report=term-missing --cov-report=xml
  #         
  #     - name: Upload coverage to Codecov
  #       uses: codecov/codecov-action@v5
  #       with:
  #         file: ./coverage.xml
  #         fail_ci_if_error: false